routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\web\ProductController;
use App\Http\Controllers\web\TransactionController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/login', function () {
    return view('login');
});

Route::controller(ProductController::class)
    ->prefix('web/product')
    ->name('web.product.')
    ->group(function (){
        Route::get('/', 'index')->name('index');
        Route::post('/store', 'store')->name('store');
        Route::get('/show/{id}', 'show')->name('show');
        Route::post('/update/{id}', 'update')->name('update');
        Route::post('/delete', 'destroy')->name('delete');
    });

Route::controller(TransactionController::class)
    ->prefix('web/transaction')
    ->name('web.transaction.')
    ->group(function (){
        Route::get('/', 'index')->name('index');
        Route::post('/store', 'store')->name('store');
        Route::get('/show/{id}', 'show')->name('show');
        Route::post('/update/{id}', 'update')->name('update');
        Route::post('/delete', 'destroy')->name('delete');
    });

resources/views/login.blade.php
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Login</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <style>
        .bd-placeholder-img {
            font-size: 1.125rem;
            text-anchor: middle;
            -webkit-user-select: none;
            -moz-user-select: none;
            user-select: none;
        }

        @media (min-width: 768px) {
            .bd-placeholder-img-lg {
                font-size: 3.5rem;
            }
        }

        .b-example-divider {
            height: 3rem;
            background-color: rgba(0, 0, 0, .1);
            border: solid rgba(0, 0, 0, .15);
            border-width: 1px 0;
            box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em rgba(0, 0, 0, .15);
        }

        .b-example-vr {
            flex-shrink: 0;
            width: 1.5rem;
            height: 100vh;
        }

        .bi {
            vertical-align: -.125em;
            fill: currentColor;
        }

        .nav-scroller {
            position: relative;
            z-index: 2;
            height: 2.75rem;
            overflow-y: hidden;
        }

        .nav-scroller .nav {
            display: flex;
            flex-wrap: nowrap;
            padding-bottom: 1rem;
            margin-top: -1px;
            overflow-x: auto;
            text-align: center;
            white-space: nowrap;
            -webkit-overflow-scrolling: touch;
        }
    </style>
    <!-- Custom styles for this template -->
    <link href="https://getbootstrap.com/docs/5.3/examples/sign-in/sign-in.css" rel="stylesheet">
</head>
<body class="text-center">

<main class="form-signin w-100 m-auto">
    <form action="/api/login" method="post">
        <img class="mb-4" src="https://baysptr.my.id/images/garuda.png" width="120">
        <h1 class="h3 mb-3 fw-normal">Please sign in</h1>

        <div class="form-floating">
            <input type="email" name="email" class="form-control" id="floatingInput" placeholder="name@example.com">
            <label for="floatingInput">Email address</label>
        </div>
        <div class="form-floating">
            <input type="password" name="password" class="form-control" id="floatingPassword" placeholder="Password">
            <label for="floatingPassword">Password</label>
        </div>

        <button class="w-100 btn btn-lg btn-primary" type="submit">Sign in</button>
    </form>
</main>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.min.js" integrity="sha384-mQ93GR66B00ZXjt0YO5KlohRA5SY2XofN4zfuZxLkoj1gXtW8ANNCe9d5Y3eG5eD" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
</body>
</html>

resources/views/product.blade.php
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Datautama | Product</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.3.0/css/all.min.css"
          integrity="sha512-SzlrxWUlpfuzQ+pcUCosxcglQRNAq/DZjVsC0lE40xsADsfeQoEypE+enwcOiGjk/bSuGGKHEyjSoQ1zVisanQ=="
          crossorigin="anonymous" referrerpolicy="no-referrer"/>
</head>
<body>

<header>
    <!-- Fixed navbar -->
    <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
        <div class="container-fluid">
            <a class="navbar-brand" href="#">Data Utama</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse"
                    aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarCollapse">
                <ul class="navbar-nav me-auto mb-2 mb-md-0">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{{route('web.product.index')}}">Product</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{route('web.transaction.index')}}">Transaction</a>
                    </li>
                </ul>
                <form class="d-flex" role="search">
                    <button class="btn btn-outline-warning">Logout</button>
                </form>
            </div>
        </div>
    </nav>
</header>
<br/><br/>

<main class="container mt-5">
    <table class="table table-bordered mb-5">
        <thead>
        <tr>
            <th colspan="5">
                <form action="{{route('web.product.index')}}" method="get">
                    <input type="text" name="search" value="{{$s}}" class="form-control"
                           placeholder="Search Name Product">
                </form>
            </th>
            <th colspan="2">
                <div class="btn btn-dark w-100" onclick="addProduct()"><i class="fa-solid fa-plus"></i></div>
            </th>
        </tr>
        <tr class="table-success">
            <th>#</th>
            <th>Name</th>
            <th width="160">Price</th>
            <th>Stock</th>
            <th>Description</th>
            <th colspan="2">Act</th>
        </tr>
        </thead>
        <tbody>
        @foreach($datas as $data)
            <tr>
                <th scope="row">{{ $data->id }}</th>
                <td>{{ $data->name }}</td>
                <td>@currency($data->price)</td>
                <td>{{ $data->stock }}</td>
                <td>{{ $data->description }}</td>
                <td>
                    <div class="btn btn-sm btn-primary w-100" onclick="editProduct('{{$data->id}}')"><i class="fa-solid fa-pen-to-square"></i></div>
                </td>
                <td>
                    <div class="btn btn-sm btn-warning w-100" onclick="deleteProduct('{{$data->id}}')"><i class="fa-solid fa-delete-left"></i></div>
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>
    {{-- Pagination --}}
    <div class="d-flex justify-content-center">
        {!! $datas->links() !!}
    </div>
</main>

<div class="modal" id="productModal" tabindex="-1">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Modal title</h5>
                <button type="button" class="btn-close" onclick="closeProduct()" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form id="formProduct">
                    <input type="hidden" name="id" id="id">
                    @csrf
                    <div class="mb-3">
                        <label class="form-label">Product Name</label>
                        <input type="text" name="name" id="name" placeholder="Product Name" class="form-control" required>
                    </div>
                    <div class="mb-3">
                        <label class="form-label">Product Price</label>
                        <input type="number" name="price" id="price" placeholder="Product Price" class="form-control" required>
                    </div>
                    <div class="mb-3">
                        <label class="form-label">Product Stock</label>
                        <input type="number" name="stock" id="stock" placeholder="Product Stock" class="form-control" required>
                    </div>
                    <div class="mb-3">
                        <label class="form-label">Product Description</label>
                        <textarea name="description" id="description" class="form-control" required placeholder="Product Description"></textarea>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" onclick="closeProduct()">Close</button>
                <button type="button" class="btn btn-primary" id="btnAct" onclick="submitProduct()">Save changes</button>
            </div>
        </div>
    </div>
</div>

<script src="https://code.jquery.com/jquery-3.6.4.min.js" integrity="sha256-oP6HI9z1XaZNBrJURtCoUT5SUnxFr8s3BzRl+cbzUq8=" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.min.js"
        integrity="sha384-mQ93GR66B00ZXjt0YO5KlohRA5SY2XofN4zfuZxLkoj1gXtW8ANNCe9d5Y3eG5eD"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js"
        integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.3.0/js/all.min.js"
        integrity="sha512-2bMhOkE/ACz21dJT8zBOMgMecNxx0d37NND803ExktKiKdSzdwn+L7i9fdccw/3V06gM/DBWKbYmQvKMdAA9Nw=="
        crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<script>
    function addProduct(){
        $(".modal-title").html('Form Add Product!');
        $("#btnAct").html('Tambah!')
        $("#productModal").modal('show');
    }

    function closeProduct(){
        $(".modal-title").html('');
        $("#id").val("");
        $("#name").val("");
        $("#price").val("");
        $("#stock").val("");
        $("#description").val("");
        $("#productModal").modal('hide');
    }

    function editProduct(id){
        $.get('/web/product/show/'+id, function (resp){
            if(resp.message === 'SUCCESS'){
                $(".modal-title").html('Form Update Product!');
                $("#btnAct").html('Ubah!')
                $("#id").val(resp.data.id);
                $("#name").val(resp.data.name);
                $("#price").val(resp.data.price);
                $("#stock").val(resp.data.stock);
                $("#description").val(resp.data.description);
                $("#productModal").modal('show');
            }else{
                alert('Maaf telah terjadi kesalahan pada sistem');
            }
        })
    }

    function deleteProduct(id){
        if(confirm("Apakah anda yakin untuk hapus data ini?")===true){
            $.ajax({
                url: '{{route('web.product.delete')}}',
                type: 'POST',
                data: {id: id, "_token": "{{ csrf_token() }}"},
                success: function (resp){
                    if(resp.message === 'DELETED'){
                        location.reload();
                    }else{
                        alert('Maaf telah terjadi kesalahan sistem');
                        closeProduct();
                    }
                }
            })
        }
    }

    function submitProduct(){
        id = $("#id").val();
        if(id === "" || id === null){
            $.ajax({
                url: '{{route('web.product.store')}}',
                type: 'POST',
                data: $("#formProduct").serialize(),
                success: function (resp){
                    if(resp.message === 'INSERTED'){
                        location.reload();
                    }else{
                        alert('Maaf telah terjadi kesalahan sistem');
                        closeProduct();
                    }
                }
            })
        }else{
            $.ajax({
                url: '/web/product/update/'+id,
                type: 'POST',
                data: $("#formProduct").serialize(),
                success: function (resp){
                    if(resp.message === 'UPDATED'){
                        location.reload();
                    }else{
                        alert('Maaf telah terjadi kesalahan sistem');
                        closeProduct();
                    }
                }
            })
        }
    }
</script>
</body>
</html>

resources/views/transaction.blade.php
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Datautama | Transaction</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.3.0/css/all.min.css"
          integrity="sha512-SzlrxWUlpfuzQ+pcUCosxcglQRNAq/DZjVsC0lE40xsADsfeQoEypE+enwcOiGjk/bSuGGKHEyjSoQ1zVisanQ=="
          crossorigin="anonymous" referrerpolicy="no-referrer"/>
</head>
<body>

<header>
    <!-- Fixed navbar -->
    <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
        <div class="container-fluid">
            <a class="navbar-brand" href="#">Data Utama</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse"
                    aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarCollapse">
                <ul class="navbar-nav me-auto mb-2 mb-md-0">
                    <li class="nav-item">
                        <a class="nav-link" aria-current="page" href="{{route('web.product.index')}}">Product</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" href="{{route('web.transaction.index')}}">Transaction</a>
                    </li>
                </ul>
                <form class="d-flex" role="search">
                    <button class="btn btn-outline-warning">Logout</button>
                </form>
            </div>
        </div>
    </nav>
</header>
<br/><br/>

<main class="container mt-5">
    <table class="table table-bordered mb-5">
        <thead>
        <tr>
            <th colspan="6">
                <form action="{{route('web.transaction.index')}}" method="get">
                    <input type="text" name="search" value="{{$s}}" class="form-control"
                           placeholder="Search Name Product">
                </form>
            </th>
            <th colspan="2">
                <div class="btn btn-dark w-100" onclick="addProduct()"><i class="fa-solid fa-plus"></i></div>
            </th>
        </tr>
        <tr class="table-success">
            <th>#</th>
            <th>No Reference</th>
            <th width="160">Price</th>
            <th>Quantity</th>
            <th>Payment Amount</th>
            <th>Product</th>
            <th colspan="2">Act</th>
        </tr>
        </thead>
        <tbody>
        @foreach($datas as $data)
            <tr>
                <th scope="row">{{ $data->id }}</th>
                <td>{{ $data->reference_no }}</td>
                <td>@currency($data->price)</td>
                <td>{{ $data->quantity }}</td>
                <td>{{ $data->payment_amount }}</td>
                <td>{{ $data->product->name }}</td>
                <td>
                    <div class="btn btn-sm btn-primary w-100" onclick="editProduct('{{$data->id}}')"><i class="fa-solid fa-pen-to-square"></i></div>
                </td>
                <td>
                    <div class="btn btn-sm btn-warning w-100" onclick="deleteProduct('{{$data->id}}')"><i class="fa-solid fa-delete-left"></i></div>
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>
    {{-- Pagination --}}
    <div class="d-flex justify-content-center">
        {!! $datas->links() !!}
    </div>
</main>

<div class="modal" id="productModal" tabindex="-1">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Modal title</h5>
                <button type="button" class="btn-close" onclick="closeProduct()" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form id="formProduct">
                    <input type="hidden" name="id" id="id">
                    @csrf
                    <div class="mb-3">
                        <label class="form-label">Product Name</label>
                        <select name="product_id" id="product_id" class="form-control">
                            @foreach($products as $product)
                                <option value="{{$product->id}}">{{$product->name}}</option>
                            @endforeach
                        </select>
                    </div>
                    <div class="mb-3">
                        <label class="form-label">Transaction Price</label>
                        <input type="number" name="price" id="price" placeholder="Transaction Price" class="form-control" required>
                    </div>
                    <div class="mb-3">
                        <label class="form-label">Transaction Quantity</label>
                        <input type="number" name="quantity" id="quantity" placeholder="Transaction Quantity" class="form-control" required>
                    </div>
                    <div class="mb-3">
                        <label class="form-label">Transaction Payment Amount</label>
                        <input type="number" name="payment_amount" id="payment_amount" placeholder="Transaction Payment Amount" class="form-control" required>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" onclick="closeProduct()">Close</button>
                <button type="button" class="btn btn-primary" id="btnAct" onclick="submitProduct()">Save changes</button>
            </div>
        </div>
    </div>
</div>

<script src="https://code.jquery.com/jquery-3.6.4.min.js" integrity="sha256-oP6HI9z1XaZNBrJURtCoUT5SUnxFr8s3BzRl+cbzUq8=" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.min.js"
        integrity="sha384-mQ93GR66B00ZXjt0YO5KlohRA5SY2XofN4zfuZxLkoj1gXtW8ANNCe9d5Y3eG5eD"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js"
        integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.3.0/js/all.min.js"
        integrity="sha512-2bMhOkE/ACz21dJT8zBOMgMecNxx0d37NND803ExktKiKdSzdwn+L7i9fdccw/3V06gM/DBWKbYmQvKMdAA9Nw=="
        crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<script>
    function addProduct(){
        $(".modal-title").html('Form Add Transaction!');
        $("#btnAct").html('Tambah!')
        $("#productModal").modal('show');
    }

    function closeProduct(){
        $(".modal-title").html('');
        $("#id").val("");
        $("#product_id").val("");
        $("#price").val("");
        $("#quantity").val("");
        $("#payment_amount").val("");
        $("#productModal").modal('hide');
    }

    function editProduct(id){
        $.get('/web/transaction/show/'+id, function (resp){
            if(resp.message === 'SUCCESS'){
                $(".modal-title").html('Form Update Transaction!');
                $("#btnAct").html('Ubah!')
                $("#id").val(resp.data.id);
                $("#product_id").val(resp.data.product_id);
                $("#price").val(resp.data.price);
                $("#quantity").val(resp.data.quantity);
                $("#payment_amount").val(resp.data.payment_amount);
                $("#productModal").modal('show');
            }else{
                alert('Maaf telah terjadi kesalahan pada sistem');
            }
        })
    }

    function deleteProduct(id){
        if(confirm("Apakah anda yakin untuk hapus data ini?")===true){
            $.ajax({
                url: '{{route('web.transaction.delete')}}',
                type: 'POST',
                data: {id: id, "_token": "{{ csrf_token() }}"},
                success: function (resp){
                    if(resp.message === 'DELETED'){
                        location.reload();
                    }else{
                        alert('Maaf telah terjadi kesalahan sistem');
                        closeProduct();
                    }
                }
            })
        }
    }

    function submitProduct(){
        id = $("#id").val();
        if(id === "" || id === null){
            $.ajax({
                url: '{{route('web.transaction.store')}}',
                type: 'POST',
                data: $("#formProduct").serialize(),
                success: function (resp){
                    if(resp.message === 'INSERTED'){
                        location.reload();
                    }else{
                        alert('Maaf telah terjadi kesalahan sistem');
                        closeProduct();
                    }
                }
            })
        }else{
            $.ajax({
                url: '/web/transaction/update/'+id,
                type: 'POST',
                data: $("#formProduct").serialize(),
                success: function (resp){
                    if(resp.message === 'UPDATED'){
                        location.reload();
                    }else{
                        alert('Maaf telah terjadi kesalahan sistem');
                        closeProduct();
                    }
                }
            })
        }
    }
</script>
</body>
</html>